apiVersion: v1
kind: Service
metadata:
  name: memorandum-fe-service
spec:
  type: LoadBalancer
  selector:
    app: memorandum-fe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8050
  externalIPs:
  - "34.172.80.103"
